### ISSUE TITLE
tree order is reversed

### ISSUE THREAD

**Issue by sdementen** [eviltnan/kivy-autotesting-example#2]
Hello,

While using your testing tool, I notice that the tree is revered (ie the order of children are in the opposite direction). Something like:

```
simulator.assert_text("//BoxLayout/Label[1]", "some text")
```

will test for the last Label of the BoxLayout instead of the first.

Reversing the order of the children traversal in the build_deep function fixes that:

```
for child in widget.children[::-1]:
    element.append(self.build_deep(child))
```

**Comment by thorin-schiffer** [comment]
Hey, can you make a PR please?
